# Generated by Django 5.2.17 on 2026-09-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('student_name', models.CharField(max_length=220, verbose_name='Студент')),
                ('course_title', models.CharField(max_length=220, verbose_name='Курс')),
                ('exam_points', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Экзамен (макс. 70)')),
                ('assignment_points', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Задания (макс. 25)')),
                ('activity_points', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Активность (макс. 5)')),
                ('total_points', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Итого (макс. 100)')),
                ('passed', models.BooleanField(default=False, verbose_name='Зачёт (порог 60)')),
                ('code', models.CharField(editable=False, max_length=8, unique=True, verbose_name='Код выписки')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='courses.enrollment', verbose_name='Запись на курс')),
            ],
            options={
                'verbose_name': 'Академическая выписка',
                'verbose_name_plural': 'Академические выписки',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата встречи')),
                ('present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Заметка')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='courses.enrollment', verbose_name='Запись на курс')),
            ],
            options={
                'verbose_name': 'Посещение встречи',
                'verbose_name_plural': 'Посещение встреч',
                'ordering': ('enrollment', 'date'),
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'date'), name='uniq_attendance_per_day')],
            },
        ),
    ]
