# Generated by Django 5.2.17 on 2026-09-13 05:26

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Квадратная картинка до 2 МБ (jpg, png, webp)', upload_to='accounts/avatars/%Y/', validators=[apps.core.validators.FileValidator(allowed_extensions=['gif', 'jpeg', 'jpg', 'png', 'webp'], max_size_mb=2)], verbose_name='Аватар'),
        ),
    ]
