# Generated by Django 5.2.17 on 2026-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_ban_reason_user_banned_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusted',
            field=models.BooleanField(default=False, verbose_name='Доверенное лицо (может отвечать на форуме)'),
        ),
    ]
