# Generated by Django 5.2.17 on 2026-09-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120, verbose_name='Название платформы')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Краткий слоган')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp (номер с кодом страны, без +)')),
                ('telegram', models.CharField(blank=True, max_length=60, verbose_name='Telegram (имя канала или @пользователя)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('about_footer', models.TextField(blank=True, verbose_name='Текст в подвале сайта')),
            ],
            options={
                'verbose_name': 'Контакты сайта',
                'verbose_name_plural': 'Контакты сайта',
            },
        ),
    ]
