# Generated by Django 5.2.17 on 2026-09-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='messengers_note',
            field=models.CharField(blank=True, default='Если сайт недоступен — отправьте решение учителю в мессенджер, приложив файл:', max_length=300, verbose_name='Пояснение к мессенджерам'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='submissions_via_messengers',
            field=models.BooleanField(default=False, help_text='Резервный способ сдачи решений, если сайт недоступен', verbose_name='Показывать на заданиях отправку через WhatsApp/Telegram'),
        ),
    ]
