# Generated by Django 5.2.17 on 2026-09-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteinfo_messengers_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='show_books',
            field=models.BooleanField(default=True, verbose_name='Показывать раздел книг в меню и на главной'),
        ),
    ]
