# Generated by Django 5.2.17 on 2026-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteinfo_show_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='donations_details',
            field=models.TextField(blank=True, help_text='Карта, счёт или ссылка — по строкам', verbose_name='Реквизиты поддержки'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='donations_text',
            field=models.CharField(blank=True, default='Проект существует на пожертвования. Помощь редакторам, переводам книг и развитию платформы — баракаЛлаху фикум.', max_length=300, verbose_name='Текст о поддержке'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='donations_title',
            field=models.CharField(blank=True, default='Поддержать проект', max_length=120, verbose_name='Заголовок блока поддержки'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='payment_details',
            field=models.TextField(blank=True, help_text='Номер карты/счёта, имя получателя, куда присылать чек. Видит только сам студент на странице платежей', verbose_name='Реквизиты для оплаты'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_donations',
            field=models.BooleanField(default=False, verbose_name='Показывать блок «Поддержать проект» в подвале'),
        ),
    ]
