# Generated by Django 5.2.17 on 2026-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteinfo_donations_details_siteinfo_donations_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='forum_comments_enabled',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы закрыть комментарии во всех темах сразу', verbose_name='Комментарии на форуме включены (все темы)'),
        ),
    ]
