# Generated by Django 5.2.17 on 2026-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteinfo_forum_comments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='adsense_client_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='AdSense Client ID (ca-pub-…)'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='adsense_enabled',
            field=models.BooleanField(default=False, verbose_name='Показывать Google AdSense'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='forum_enabled',
            field=models.BooleanField(default=True, verbose_name='Раздел «Форум» включён'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='hadith_enabled',
            field=models.BooleanField(default=True, verbose_name='Раздел «Хадисы» включён'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='library_enabled',
            field=models.BooleanField(default=True, verbose_name='Раздел «Библиотека» включён'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='secular_courses_enabled',
            field=models.BooleanField(default=False, verbose_name='Светские курсы (заготовка на будущее)'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='stories_enabled',
            field=models.BooleanField(default=False, verbose_name='Раздел «Истории» (заготовка на будущее)'),
        ),
    ]
