# Generated by Django 5.2.17 on 2026-09-12 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Адрес (латиницей)')),
                ('book', models.CharField(blank=True, help_text='Например: «Коралловые холмы», глава 1–5', max_length=200, verbose_name='Книга')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор книги')),
                ('summary', models.TextField(blank=True, verbose_name='Кратко о курсе')),
                ('description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('status', models.CharField(choices=[('soon', 'Скоро'), ('registration', 'Открыта регистрация'), ('active', 'Идёт обучение'), ('finished', 'Завершён')], default='soon', max_length=20, verbose_name='Статус')),
                ('cover', models.ImageField(blank=True, upload_to='courses/covers/', verbose_name='Обложка')),
                ('registration_start', models.DateField(blank=True, null=True, verbose_name='Начало регистрации')),
                ('registration_end', models.DateField(blank=True, null=True, verbose_name='Конец регистрации')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец обучения')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок в программе')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Адрес (латиницей)')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок вывода')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('status', models.CharField(choices=[('active', 'Учится'), ('completed', 'Завершил'), ('dropped', 'Бросил')], default='active', max_length=20, verbose_name='Статус')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Номер урока')),
                ('week', models.PositiveSmallIntegerField(default=1, verbose_name='Неделя')),
                ('title', models.CharField(max_length=250, verbose_name='Название урока')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('content', models.TextField(blank=True, verbose_name='Конспект урока')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube/VK)')),
                ('audio', models.FileField(blank=True, upload_to='lessons/audio/%Y/', verbose_name='Аудиофайл')),
                ('document', models.FileField(blank=True, upload_to='lessons/docs/%Y/', verbose_name='PDF-файл урока')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('course', 'order'),
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Пройден')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.enrollment', verbose_name='Запись')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Прогресс урока',
                'verbose_name_plural': 'Прогресс уроков',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.program', verbose_name='Программа'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uniq_student_per_course'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uniq_lesson_order_in_course'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='uniq_progress_per_lesson'),
        ),
    ]
