# Generated by Django 5.2.17 on 2026-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Курс открыт без зачисления: любой зарегистрированный может проходить уроки и тесты как свободный слушатель (решает админ)', verbose_name='Свободный доступ'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Учится'), ('completed', 'Завершил'), ('dropped', 'Бросил'), ('listener', 'Слушатель (свободно)')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
