# Generated by Django 5.2.17 on 2026-09-13 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_is_free_alter_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('kind', models.CharField(choices=[('admission', 'Поступление (взнос)'), ('tuition', 'Обучение (семестр/курс)'), ('other', 'Другое')], default='tuition', max_length=12, verbose_name='За что')),
                ('title', models.CharField(help_text='Например: Оплата за семестр, осень 2026', max_length=200, verbose_name='Назначение')),
                ('total', models.PositiveIntegerField(verbose_name='Сумма всего, сум')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Заметка для студента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='courses.course', verbose_name='Курс (необязательно)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Счёт на оплату',
                'verbose_name_plural': 'Счета на оплату',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='№ платежа')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма, сум')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплатить до')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления')),
                ('method', models.CharField(blank=True, max_length=80, verbose_name='Способ (для заметки)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.invoice', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Платёж по графику',
                'verbose_name_plural': 'График платежей',
                'ordering': ('invoice', 'number'),
                'constraints': [models.UniqueConstraint(fields=('invoice', 'number'), name='uniq_installment_number')],
            },
        ),
    ]
