# Generated by Django 5.2.17 on 2026-09-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Для себя: «Главная — между записями»', max_length=100, verbose_name='Название слота')),
                ('location', models.CharField(choices=[('header', 'Под шапкой'), ('sidebar', 'Сбоку'), ('between_posts', 'Между записями (лента главной)'), ('footer', 'Над подвалом')], max_length=20, unique=True, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Слот активен')),
            ],
            options={
                'verbose_name': 'Рекламный слот',
                'verbose_name_plural': 'Рекламные слоты',
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('advertiser_name', models.CharField(blank=True, max_length=150, verbose_name='Кто разместил')),
                ('image', models.ImageField(blank=True, upload_to='ads/images/', verbose_name='Картинка')),
                ('video', models.FileField(blank=True, upload_to='ads/video/', verbose_name='Видео')),
                ('audio', models.FileField(blank=True, upload_to='ads/audio/', verbose_name='Аудио')),
                ('link_url', models.URLField(blank=True, verbose_name='Куда ведёт')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='Показывать с')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Показывать до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.adslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Рекламный материал',
                'verbose_name_plural': 'Рекламные материалы',
                'ordering': ('-created_at',),
            },
        ),
    ]
