# Generated by Django 5.2.17 on 2026-09-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=160, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, upload_to='books/covers/', verbose_name='Обложка')),
                ('price', models.CharField(blank=True, max_length=60, verbose_name='Цена (надпись)')),
                ('order_url', models.URLField(blank=True, verbose_name='Ссылка для заказа (магазин/пост)')),
                ('order_note', models.CharField(blank=True, default='Заказать', max_length=80, verbose_name='Подпись к кнопке')),
                ('order_pub', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок вывода')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('order_pub', 'pk'),
            },
        ),
    ]
