# Generated by Django 5.2.17 on 2026-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kind',
            field=models.CharField(choices=[('free', 'Бесплатные (скачать)'), ('online', 'Онлайн-книги (читать)'), ('paid', 'Продаются')], default='paid', help_text='Бесплатные и онлайн-книги открываются по ссылке «Читать»', max_length=10, verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='book',
            name='read_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на чтение/скачивание'),
        ),
    ]
