# Generated by Django 5.2.17 on 2026-09-12 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('week', models.PositiveSmallIntegerField(default=1, verbose_name='Неделя')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Текст задания')),
                ('max_points', models.PositiveSmallIntegerField(default=5, verbose_name='Максимум баллов')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Сдать до')),
                ('allow_file', models.BooleanField(default=False, verbose_name='Разрешить файл в ответе')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('course', 'week', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('file', models.FileField(blank=True, upload_to='assignments/%Y/', verbose_name='Файл ответа')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('graded', 'Проверено')], default='submitted', max_length=10, verbose_name='Статус')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Баллы')),
                ('feedback', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Задание')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='uniq_submission')],
            },
        ),
    ]
