# Generated by Django 5.2.17 on 2026-09-12 19:53

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='allow_file',
            field=models.BooleanField(default=True, help_text='Фото, аудио, PDF и другие документы', verbose_name='Разрешить файл в ответе'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, upload_to='assignments/%Y/', validators=[apps.core.validators.FileValidator(allowed_extensions=['aac', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'ogg', 'pdf', 'png', 'txt', 'wav', 'webm', 'webp', 'zip'], max_size_mb=100)], verbose_name='Файл ответа (фото / аудио / PDF)'),
        ),
    ]
