# Generated by Django 5.2.17 on 2026-09-12 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание / инструкция')),
                ('kind', models.CharField(choices=[('final', 'Итоговый экзамен'), ('module', 'Промежуточный тест')], default='final', max_length=10, verbose_name='Тип')),
                ('time_limit_min', models.PositiveSmallIntegerField(default=45, verbose_name='Лимит времени, минут')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Максимум попыток')),
                ('pass_percent', models.PositiveSmallIntegerField(default=60, verbose_name='Порог зачёта, %')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тест / экзамен',
                'verbose_name_plural': 'Тесты и экзамены',
                'ordering': ('course', 'kind', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('points_earned', models.PositiveSmallIntegerField(default=0, verbose_name='Набрано баллов')),
                ('points_max', models.PositiveSmallIntegerField(default=0, verbose_name='Максимум баллов')),
                ('score_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Результат, %')),
                ('passed', models.BooleanField(default=False, verbose_name='Зачёт')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Попытка прохождения',
                'verbose_name_plural': 'Попытки прохождения',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('q_type', models.CharField(choices=[('single', 'Один ответ'), ('multi', 'Несколько ответов')], default='single', max_length=10, verbose_name='Тип вопроса')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Баллы')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('exam', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('text', models.CharField(max_length=400, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ('question', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Баллы')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('attempt', 'question__order'),
            },
        ),
    ]
