# Generated by Django 5.2.17 on 2026-09-12 19:53

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Комментарий учителя'),
        ),
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, upload_to='exam-answers/%Y/', validators=[apps.core.validators.FileValidator(allowed_extensions=['aac', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'ogg', 'pdf', 'png', 'txt', 'wav', 'webm', 'webp', 'zip'], max_size_mb=100)], verbose_name='Файл ответа (фото/аудио/PDF)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='needs_grading',
            field=models.BooleanField(default=False, verbose_name='Ждёт оценки учителя'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('single', 'Один ответ'), ('multi', 'Несколько ответов'), ('open', 'Свободный ответ (проверяет учитель)')], default='single', max_length=10, verbose_name='Тип вопроса'),
        ),
    ]
