# Generated by Django 5.2.17 on 2026-09-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('text', models.TextField(verbose_name='Текст хадиса')),
                ('source', models.CharField(blank=True, help_text='Например: Сахих аль-Бухари, №13', max_length=200, verbose_name='Источник')),
                ('narrator', models.CharField(blank=True, max_length=200, verbose_name='Передатчик')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Хадис',
                'verbose_name_plural': 'Хадисы',
                'ordering': ('id',),
            },
        ),
    ]
