# Generated by Django 5.2.17 on 2026-09-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=250, verbose_name='Тема встречи')),
                ('description', models.TextField(blank=True, verbose_name='Описание / план')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('duration_min', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность, минут')),
                ('link', models.URLField(blank=True, help_text='Zoom / Google Meet / YouTube-трансляция. Видна записавшимся.', verbose_name='Ссылка подключения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('course', models.ForeignKey(blank=True, help_text='Пусто — общая встреча платформы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Онлайн-встреча',
                'verbose_name_plural': 'Онлайн-встречи',
                'ordering': ('starts_at',),
            },
        ),
    ]
