# Generated by Django 5.2.17 on 2026-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='Официальный ответ учителя'),
        ),
        migrations.AddField(
            model_name='thread',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Комментарии разрешены'),
        ),
        migrations.AddField(
            model_name='thread',
            name='visibility',
            field=models.CharField(choices=[('public', 'Видно всем'), ('teachers', 'Видно учителям (приватный вопрос)')], default='public', max_length=10, verbose_name='Кто видит'),
        ),
        migrations.AddField(
            model_name='thread',
            name='who_can_answer',
            field=models.CharField(choices=[('anyone', 'Отвечают все'), ('teachers', 'Отвечают учителя и доверенные')], default='anyone', max_length=10, verbose_name='Кто может отвечать'),
        ),
    ]
